[client]
showErrorDetails = true
toolbarMode = "developer"

[logger]
level = "info"

[server]
runOnSave = true
headless = true
port = 8501
address = "localhost"

[theme]
base = "light"
primaryColor = "#0066cc"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"
